name: 'Set up Node.js'
description: 'Install Node.js and development dependencies'

inputs:
  node-version:
    description: 'Node.js version to install'
    default: '18'

runs:
  using: 'composite'
  steps:
    - name: 'Install pnpm'
      uses: pnpm/action-setup@v2

    - name: 'Install Node.js'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: 'Install development dependencies'
      shell: bash
      run: pnpm install --frozen-lockfile
