name: Continuous integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Install 🔧'
        uses: ./.github/actions/setup
      - name: 'Run checks ✅'
        run: pnpm all
